Cassiopee/Connector/Connector/IBM.py
Cassiopee/Generator/Generator/IBM.py

Towards unifying the IBM prep approach. Add functionalities found in Apps/IBM.py to the macro functions found in the IBM.py file for the Cassiopee Modules (e.g. connector).
Functionalities transposed:
1) Rectilinear Mesh
2) F1 & F42 cohabiting for the same geometry/surface mesh.

[IBM] Add rectilinear mesh capabilities to Connector/IBM.py IBM prep approach. Copy functionality from Apps/IBM.py.

---

Cassiopee/Generator/Generator/close.cpp
Cassiopee/KCore/KCore/Array/Array.h
Cassiopee/KCore/installLib.py
Cassiopee/KCore/test/notifyInstall.py

- booleans map to C int in int32 and int64, create B in Array.h
- any user can receive an update listing the machines on which Cassiopee is installed, their date and their status (OK/FAILED)
+ set the env. variable `CASSIOPEE_EMAIL` as `export CASSIOPEE_EMAIL=firstname.lastname@onera.fr`
+ execute the following command: `python $CASSIOPEE/Cassiopee/KCore/test/notifyInstall.py`
Example:
```
Installation of Cassiopee and Fast:
----------------------------------
ld |      17/06/24 at 14:54:10      |         OK
sator_cas_i8 |      17/06/24 at 14:25:15      |         OK
spiro_el8_i8 |      17/06/24 at 14:05:34      |         OK
sator_cas |      17/06/24 at 14:00:39      |         OK
spiro_el8 |      17/06/24 at 14:00:23      |         OK
```

KCore: booleans in i8 and notifications

---

Cassiopee/Post/Post/PyTree.py

From ZoneSubRegion_t to UserDefinedData_t.
Warning: small regression with prepareSkinReconstructionPT_t1 !

Post and Post_IBM: change node type for MLS data stored in surface tree

---

Cassiopee/Connector/Connector/IBM.py
Cassiopee/Distributor2/Distributor2/Mpi.py

Reduces the risk of memory overflows during tree redispatching at the end of IBM preprocessing
Connector.IBM : removes ZoneSubRegion_t from skeleton tree (ID* and IBCD* zones)
Distributor2.Mpi : splits addXZones into (Cmpi.size - 1)*addXZones

Connector.IBM: optimize final distribution operations

---

Cassiopee/CPlot/apps/validCassiopee.py
Cassiopee/KCore/test/compareSessionLogs.py

- compareSessionLogs: add state called `DELETIONS` that is a _passing_ state, ie, a reference session log is created when some tests are deleted **and** no other tests fail
- validCassiopee: update tests from command line:
Run a test
```sh
validCassiopee --load-session --filters='getNCells_t1' --run
```
Update a test
```sh
validCassiopee --load-session --filters='getNCells_t1' --update
```

KCore/CPlot: compareSessionLogs, validCassiopee

---

Cassiopee/CPlot/apps/validCassiopee.py

- fix crash when loading previous session and none exists
- fix hang when running cases from modules that are in the global db but not in the local db: only common modules are shown in the list

CPlot - validCassiopee: minor fixes

---

Cassiopee/Connector/Connector/IBM.py
Cassiopee/Connector/test/prepareIBMData_m1.py
Cassiopee/Connector/test/prepareIBMData_t1.py

The current implementation of the redispatch yields t's with difference. As such, a non-regression test with this function activated during the MPI IBM Cartesian mesh generation fails. This is a **temporary bug patch** (not fix) till a more permanent solution can be found - not yet able to find the root cause. 
2 test cases are added: a serial and mpi test case for MPI mesh generation. These are needed as the latter was not previously available.  The serial mesh generation test cases are for the legacy mesh generation approach - thereby making the former test cases necessary also.

[IBM] Temporary bug fix for IBM mesh generation (MPI) to yield exactly the same t and tc. Test cases added also.

---

Cassiopee/Apps/test/FastIBMWireMeshModel_m1.py
Cassiopee/Apps/test/FastIBMWireMeshModel_t1.py
Cassiopee/Connector/Connector/IBM.py
Cassiopee/Connector/test/prepareIBMData_m1.py
Cassiopee/Connector/test/prepareIBMData_t1.py

Update the Wire Mesh model test cases. The current results for _m1 are correct and should override the previous results. _t1 should not regress. 
This commit is dependent the previous **temporary bug patch** commit.

[IBM] Update Wire Mesh Model test cases

---

Cassiopee/Generator/Generator/Generator.py
Cassiopee/Generator/Generator/PyTree.py
Cassiopee/Generator/Generator/close.cpp
Cassiopee/Generator/test/closePT_t1.py
Cassiopee/Generator/test/close_t1.py
Cassiopee/KCore/KCore/Connect/connect.h
Cassiopee/KCore/KCore/Connect/v_cleanConnectivity.cpp

Define an empty list, `indices`, and pass it in the form of a keyworded argument to `G.close` or `G._close` as
```py
indices = []
G._close(t, tol=1.e-12, indices=indices)
```
`indices` will contain the vertex indirection table following mesh cleaning. Values of -1 mean that these vertices were deleted (ie, tagged as orphans or duplicates).
If `indices` is set to None (or not passed), the  vertex indirection table is not returned.
This could be used to update boundary face indices post-cleaning without resorting to `C.identifyNodes`

Generator: closeMesh: conditionally export vertex indirection table

---

Cassiopee/Converter/Converter/Internal.py
Cassiopee/Converter/test/copySortPT.py
Cassiopee/Converter/test/copySortPT_t1.py

The copySort function allows the node order to be copied between trees (e.g. between t and tc).
copySort will soon replace sortByName in Fast during warmup.

Internal: new function copySort

---

Cassiopee/Converter/Converter/kpython
Cassiopee/Envs/env_Cassiopee_local
Cassiopee/Envs/sh_Cassiopee_local
Cassiopee/KCore/installBase.py

Note: these arguments 
`--bind-to core --map-by socket:PE=$NTHREADS --report-bindings -x OMP_PROC_BIND=TRUE -x OMP_DISPLAY_ENV=VERBOSE`
are slowing _kpython_ down by about 30% on juno

Envs + kpython: adding prod juno_coda

---

Cassiopee/Apps/Apps/Fast/FastIBM.py
Cassiopee/Post/Post/Probe.py

Probe: small bugfix when fields input is a list argument to avoid changing the list after probe initialization. (For example, if the user typed fields=listOfFields where listOfFields=['centers:Mach'], the listOfFields would simply become ['Mach'] after calling probe.probe()). 
Apps: new FastIBM submodule that uses existing compute Python scripts from applied units. These new functions aim to generalize some function behavior for probes in IBM (for both surfaces and points) and simplify future compute scripts. These have been tested on real 3D cases, both sequentially and in parallel. New test cases are planned.

Apps: First version of the new FastIBM submodule

---

Cassiopee/Connector/Connector/includeTransfers_LBM_feq.h
Cassiopee/Connector/Connector/includeTransfers_coarse2fine_LBM.h
Cassiopee/Connector/Connector/includeTransfers_fine2coarse_LBM.h
Cassiopee/Connector/Connector/setInterpTransfers.cpp

Changes to the Connector module for LBM transfers. 
There have been two main changes: 
- scaling is now done in the transfer, 
- and support for D3Q19 and D3Q27 lattices has been added to each include.

Connector: modif for dimensional/non-dimensional LB transfers and D3Q19/D3Q27 support.

---

Cassiopee/Post/Post/IBM.py

See title. Comments in code to explain the temporary need in more detail.

[IBM] Post - option to revert to old projection in case it is needed Temporary and with comments. Replicating behavior seen in extractIBMWallFields.

---

Cassiopee/CPlot/apps/tkTransform.py
Cassiopee/CPlot/apps/validCassiopee.py
Cassiopee/Converter/Converter/kpython
Cassiopee/Envs/sh_Cassiopee_local
Cassiopee/KCore/KCore/test.py
tools/test_scanner.py

- KCore - test: minor fix in test.py when nodes differ by type and not by value, in which case print types
- CPlot: validCassiopee: comparison against global valid by default
- Tools: add test scanner listing non-internal functions that aren't tested yet
- Envs: prod juno_coda: restore original mpirun args, move env. args to Envs/ folder, point to CODA 08/2024

CPlot/Envs: validCassiopee defaults to global, add test scanner

---

Cassiopee/CPlot/apps/validCassiopee.py

Test duration and tag added to the test metadata JSON dict in the ValidData folder. Use time and star file to first build the metadata file, then interrogate the JSON dict only which seems to be faster. Tags are local: markers will persist when switching to and from the local/global database. The reference history is kept down to a maximum of 5 entries.
- **May need further testing from other users before merging to _main_.**
- **Please do not push commits causing regressions while this commit is pending (metadata files already created and up-to-date on ld and juno).**
Example
```json
"Apps/IBMrotation_t1.py": {
"coverage": "0%",
"ref": [
{
"date": "27/08/24 11h15",
"hashCassiopee": "Unknown",
"hashFast": "Unknown"
}
],
"tag": " ",
"time": "0m2.49s"
},
"Apps/Mirabelle_t1.py": { …
```

CPlot: validCassiopee: test duration and tag added to test metadata

---

Cassiopee/Generator/Generator/IBM.py

This commit changes the tolerance of cellN values during octree refinement using refinement bodies (tbox) due to the center2node operations applied to this field.
The same tolerance should not be used for blanking by the IBC bodies and blanking by the tbox bodies. For the former, we want to refine the octree for every cell that has even a small part inside the fluid domain. On the other hand, to ensure that the resolution is propagated far enough, the tolerance must now be set high enough to refine the octree up to the tbox boundaries.
See the two images attached: before and after the change. Since both tolerances were set to 0.9, the refinement could fail locally near the immersed boundaries (here a LEISA multi-element airfoil).

G_IBM: modif tol. for octree refinement using tbox.

---

Cassiopee/CPlot/apps/tkIBC.py

Initialization of the tkibc applet could be wrong if tkViewMode was not defined in the user's personal config file!
Default ibctype is also changed from 'Symmetry' to 'None'.
See below for an illustration of the problem:

CPlot: small bug fix for tkibc

---

Cassiopee/Apps/Apps/Fast/IBM.py

The efficient distribution of t and tc that is used for IBMs can now be used for all types of meshes and for all useCom options.

[IBM] + more. Add the useCom option to the IBM distribute in Apps/Fast/IBM.py so it can be used for all types of meshes.

---

Cassiopee/CPlot/apps/validCassiopee.py

In `runTests` that is called as
```py
threading.Thread(target=runTests, args=(update,))
```
a call to `KCore.kcore.getOmpMaxThreads()` always returns the default maximum number of threads, for ex. 48 on juno (thanks @alexandre-suss for spotting it). Setting another number in the dedicated text box does not propagate in `runTests`.
@benoit128 , would you happen to know why that is? Please reject this PR if there's a better solution.
The code is now using the value stored in the StringVar() `Threads`.
Example
```
Info: Num threads set to 37.
Running connectMatchPT_m1.py with Nprocs=2 and Nthreads=18
[...]
Running connectMatchPT_t1.py with Nprocs=0 and Nthreads=37
```

CPlot: validCassiopee: fails to set a different number of threads

---

Cassiopee/Apps/Apps/Fast/LBM.py
Cassiopee/Apps/test/FastLBM_t1.py

This pull request refactors the Apps `LBM.py` file by removing the object-oriented programming (OOP) components. This change was motivated by the observation that the OOP paradigm was not fully utilized in the current implementation and introduced unnecessary complexity.
The test case `FastLBM_t1.py` has been updated accordingly to ensure no regression.
**Warning:** The modules `Fast`, `FastASLBM`, and `FastLBM` must be updated simultaneously with Cassiopee since they all have test cases that have been modified to no longer use the OOP paradigm.

Apps/LBM: Removing the object-oriented part from Apps LBM.py

---

Cassiopee/Apps/Apps/Fast/FastIBM.py

Changes for FastIBM:
The flow field stored in the probe object cannot be accessed directly through Internal functions. The function to control the output pressure based on the Mach extracted at a probe point is modified accordingly.
Bugfix for probe initialization and extraction at probe point when field names are already set to 'centers'.

Apps: bug fix for IBMOutletControlPressure_t1.py

---

Cassiopee/Apps/Apps/Fast/MB.py
Cassiopee/Apps/test/FastMB_m1.py
Cassiopee/Apps/test/FastMB_t1.py

This pull request refactors the Apps `MB.py` file by removing the object-oriented programming (OOP) components. This change was motivated by the observation that the OOP paradigm was not fully utilized in the current implementation and introduced unnecessary complexity.
The test cases `FastMB_t1.py` and `FastMB_m1.py` have been updated accordingly to ensure no regression.

Apps/MB: Removing the object-oriented part from Apps MB.py

---

Cassiopee/Generator/Generator/IBM.py

The area refinement for IBMs can now support an area refinement that is smaller than the smallest snear of the immersed geometry. This facilities the generation of IBMs meshes as that seen below.

[IBM] Update the area refinement functionality

---

Cassiopee/Generator/Generator/Mpi.py
Cassiopee/Generator/Generator/PyTree.py
Cassiopee/Generator/test/adaptMeshPT.py
Cassiopee/Generator/test/adaptMeshPT_m1.py
Cassiopee/Generator/test/adaptMeshPT_t1.py
Cassiopee/XCore/test/adaptMeshPT.py
Cassiopee/XCore/test/adaptMeshPT_m1.py

- One commit seems to be a merge from Christophe's ??
- Warning: intersectMeshPT.py does not work. It fails in debug mode. Do not understand what is going on. 
- Creation of a Generator.adaptMesh function, idem in Generator.Mpi. Hierarchical structure can be hung, many checks are performed. Note : unitary test adaptMeshPT_m1.py requires comms between parts and global indices of cells & faces, so a temporary file tmp.cgns is dumped and read by Filter2.loadAndSplit.

Generator: adaptMesh seq and mpi;  XCore: unitary test adaptMeshPT_m1 added

---

Cassiopee/Connector/Connector/OversetData.py
Cassiopee/Connector/doc/source/Connector.rst
Cassiopee/Generator/Generator/Generator.py
Cassiopee/Generator/Generator/extendCartGrids.cpp
Cassiopee/XCore/test/intersectMeshPT.py

Connector:getIntersectingDomains: tol in the interface (useful for wind farms configs + IBM) + doc upgrade to be consistent with the python functions
XCore: add IntersectMesh in test case: removal of adaptNGON42NGON3 (not useful hier) + add icapsuleAdapt2 => still does not work

Add tol in getIntersectingDomains

---

Cassiopee/Converter/Converter/Internal.py
Cassiopee/KCore/KCore/Connect/v_cleanConnectivity.cpp

Bug in `Internal.setElementConnectivity2` for BE/ME in api2 or api3.  
Upper bound of `ElementRange` miscalculated: it used the number of vertices per element of a  connectivity rather than the number of elements of that connectivity.
Snippet to reproduce the problem:
```py
import Converter.PyTree as C
import Converter.Internal as Internal
import Generator.PyTree as G
import numpy as np
a = G.cartHexa( (0,0,0), (1,1,1), (10,10,10) )
b = G.cartTetra( (0,0,9), (1,1,1), (10,10,10) )
c = C.mergeConnectivity(a, b, boundary=0)
n_ers = Internal.getNodesFromName(c, "ElementRange")
print(n_ers)
fields = C.getAllFields(c, 'nodes', api=3)
C.setFields(fields, c, 'nodes')
n_ers = Internal.getNodesFromName(c, "ElementRange")
print(n_ers)
```
**Regressions**:
```
Converter       : convertHO2LOPT_t1.py …
```

Converter: bug in Internal.setElementConnectivity2 for BE/ME in api3

---

Cassiopee/Connector/Connector/setInterpolations.cpp

Regressions in Connector/chimeraInfoPT_t1.py
```
Running chimeraInfoPT_t1.py with Nprocs=0 and Nthreads=16
Warning: _setInterpolations: inverse storage is mandatory if no Chimera connectivity files are written.
Zone cylindre1: interpolated=156 ; extrapolated=6 ; orphan=435
Warning: zone cylindre1 has 435 orphan points !
Zone cylindre2: interpolated=153 ; extrapolated=12 ; orphan=432
Warning: zone cylindre2 has 432 orphan points !
Reading Data_ubuntu/chimeraInfoPT_t1.ref1 (bin_pickle)...done.
DIFF: Variable=centers:DcellRatio, L0=0.000000000029, L2=0.000000000001
Reading Data_ubuntu/chimeraInfoPT_t1.ref1 (bin_pickle)...done.
DIFF: Variable=centers:DcellRatio, L0=0.000000000029, L2=0.000000000001
Zone cylindre1: interpolated=156 ; extrapolated=6 ; orphan=435
Warning: zone cylindre1 has 435 …
```

Connector: K_METRIC::compVolOfStructCell - conv Fortran to C

---

Cassiopee/Connector/Connector/AMR.py
Cassiopee/Generator/Generator/AMR.py

There should be only one regression: generateAMRMeshPT_m1 (in //, we should use one base per proc and one zone per base).

G_AMR & X_AMR: SP, AJ, and BC optimizations for AMR mesh generations

---

.gitignore
Cassiopee/Envs/sh_Cassiopee_local
Cassiopee/KCore/Dist.py
Cassiopee/KCore/README
Cassiopee/KCore/config.py
Cassiopee/KCore/install
Cassiopee/KCore/installBase.py
Cassiopee/KCore/installLib.py
Cassiopee/KCore/installer.py

[PLEASE SQUASH COMMITS]
Open to discussion and changing the names of the new files if you want.
Optional: Two untracked new files: Cassiopee/KCore/installBaseUser.py and Cassiopee/Envs/sh_Cassiopee_user (env_* also later)
Example for Cassiopee/KCore/installBaseUser.py
```py
installDict = {
'myUbuntu': [
'Linux ubuntu 24.04',
'gfortran', # f77compiler
'gfortran', # f90compiler
'gcc', # Cppcompiler
[], # CppAdditionalOptions
[], # f77AdditionalOptions
True, # useOMP
False, # static
['/usr/include', '/usr/include/hdf5/openmpi', '/usr/lib/x86_64-linux-gnu/openmpi/include'], # additionalIncludePaths
['gfortran', 'gomp'], # additionalLibs
['/usr/lib/x86_64-linux-gnu/hdf5/openmpi', '/usr/lib/x86_64-linux-gnu'], # additionalLibPaths
False, # useCuda
[] # NvccAdditionalOptions
],
}
```
Example for …

KCore/Envs: user config
