Cassiopee/Post/Post/IBM.py
=> Post.IBM: coquille dans commentaire

README.md
=> Modif README

Cassiopee/CPlot/apps/validCassiopee.py
- Classes are created for most of the tkinter objects and used in non-interactive mode
- Switch between Interactive mode and Command-line execution in the Main only
- Object names are capitalized
=> CPlot - validCassiopee: allow execution in the absence of a display environment

Cassiopee/CPlot/apps/validCassiopee.py
- read module & validdata paths locally & globally only once
- user tags are local regardless of the base being used
- remove global var CASSIOPEE
=> CPlot: validCassiopee fixes

Cassiopee/CPlot/apps/validCassiopee.py, Cassiopee/Generator/Generator/Generator.py, Cassiopee/Generator/Generator/PyTree.py, Cassiopee/Generator/Generator/close.cpp, Cassiopee/KCore/KCore/Connect/connect.h, Cassiopee/KCore/KCore/Connect/v_cleanConnectivity.cpp, Cassiopee/KCore/installLib.py, Cassiopee/KCore/test/compareSessionLogs.py, Cassiopee/KCore/test/notify.py, Cassiopee/KCore/test/notifyInstall.py
- switch to new G.close function for BE/ME
- add switches in G.close for fine tuning (NGON and BE/ME)
- add notify python script to send emails
=> KCore/Generator: switch to new close function for BE/ME

Cassiopee/Envs/sh_Cassiopee_local
Bug fix related to getting python version.
=> [Envs] Bug fix sh_Cassiopee_local.

Cassiopee/KCore/test/compareSessionLogs.py, Cassiopee/KCore/test/notifyValid.py, Cassiopee/Transform/Transform/subzone.cpp
- KCore - test: send notifications on the state of global valid bases
- Transform: subzone by faces - corrections post failed `git merge`
=> KCore, Transform :

Cassiopee/Connector/test/IBMrectilinear_t1.py
Serial automatic rectilinear mesh generation non-regression test case.
=> [IBM] Automatic recilinear mesh generation non-regression test case.

Cassiopee/Apps/test/IBMOutletControlPressure_t1.py, Cassiopee/Apps/test/IBMrotationCompute_t1.py, Cassiopee/Apps/test/IBMrotation_t1.py, Cassiopee/Apps/test/Quarantine/FastIBMWireMeshModel_m1.py, Cassiopee/Apps/test/Quarantine/FastIBMWireMeshModel_t1.py, Cassiopee/Connector/Connector/IBM.py
layer='Python' in FastS.compute is trucial. The current IBM outlet pressure control test does not support the C layer. This is because the values in the tc themselves are changed.
=> [Apps] Bug fix non-regression IBM outlet pressure control test case

Cassiopee/XCore/XCore/intersectMesh/intersectSurf.cpp
=> XCore: small fix

Cassiopee/CPlot/CPlot/Data.cpp
Force consistency with tkview default value!
=> CPlot: bug fix for solidStyle

Cassiopee/CPlot/CPlot/Data.h, Cassiopee/CPlot/CPlot/GLEW/glew.c, Cassiopee/Envs/sh_Cassiopee_local, Cassiopee/KCore/switchDebugMode.py
- Add suffix to Env in Debug mode
- Define APIENTRY in CPlot (ubuntu)
=> Envs/CPlot: debug mode and fix APIENTRY

Cassiopee/Converter/Converter/convertStruct2NGon.cpp, Cassiopee/Converter/Converter/convertUnstruct2NGon.cpp, Cassiopee/KCore/install, Cassiopee/KCore/test/compareSessionLogs, Cassiopee/KCore/test/compareSessionLogs.py
- skip unnecessary stages in V_cleanConnectivity in convertArray2NGon
- improve compareSessionLogs (print to terminal, compare using a prod. name only, conditionally update the validation log)
=> KCore/Converter: add param to cleanConnectivity

Cassiopee/Apps/test/IBMOutletControlPressure_t1.py
=> [IBM] Update non-regression test case.

Cassiopee/Converter/Converter/sendRecv.cpp, Cassiopee/Post/Post/PyTree.py
- Converter: int buffer sizes in sendRcv
- Post: node Post_MLS/offset
- Apps: file naca.cgns, format ADF -> HDF
=> All: Fixes in i8

Cassiopee/Converter/Converter/convertStruct2NGon.cpp, Cassiopee/Converter/Converter/convertUnstruct2NGon.cpp, Cassiopee/Envs/sh_Cassiopee_local, Cassiopee/Generator/Generator/close.cpp, Cassiopee/Post/Post/selectExteriorFaces.cpp
Envs
- small corrections
- adding new Ubuntu prod. `fv-az`: Function Virtual (FV) on Azure (AZ)
- env_Cassiopee_local not used in Github Actions so I left it as is
Converter/Generator
- fix memory leaks in G.close and C.convertArray2NGon
=> Envs/Converter/Generator: edits for Github Actions and fix mem leaks in G.close and C.convertArray2NGon

Cassiopee/Apps/test/FastIBMWireMeshModel_t1.py, Cassiopee/Connector/Connector/IBM.py, Cassiopee/Geom/Geom/IBM.py
The additional information required for the filament IBC is obtained in each IBM macro function and not in the overarching prepareIBMData function.
=> [IBM] Update split tb and tbFilament. Done as part of the IBM clean up of 2024.

.github/workflows/build-docker.yml, .github/workflows/publish-pypi.yml, pyproject.toml
WIP: the Github Action fails after building KCore because of missing folders (see KCore/installLib.py).
=> Publish to PyPI - v1

Cassiopee/Connector/Connector/IBM.py
=> [IBM] Clean up of prepareIBMData. Remove redundant input variables & clean up redundant boolean checks.

Cassiopee/Transform/test/addkplane_t2.py
=> [TRANSFORM] Test case for addkplane function

Cassiopee/Connector/Connector/IBM.py, Cassiopee/Generator/Generator/IBM.py, Cassiopee/Generator/test/checkCartesian_m1.py, Cassiopee/Generator/test/checkCartesian_t1.py, Cassiopee/Generator/test/checkCartesian_t2.py, Cassiopee/Generator/test/checkCartesian_t3.py
See title. Please see the notes in Connector/IBM.py towards the beginning of prepareIBMData function. Certain changes will need to be made in the near future and re-compute the ref. values for the non-regression tests.
=> [IBM] prepareIBMData: check if for t_in cartesian=True or cartesian=False.

Cassiopee/CPlot/apps/validCassiopee.py, Cassiopee/Envs/sh_Cassiopee_local, Cassiopee/KCore/install
Detecting memory leaks with LSAN rather than test repetitions
=> CPlot: validCassiopee: detecting memory leaks

Cassiopee/CPlot/apps/validCassiopee.py, Cassiopee/KCore/install
createDragonMesh must fail in debug, wasn't caught till now
=> CPlot: validCassiopee: improving error detection

Cassiopee/Connector/Connector/blankIntersectingCells.cpp, Cassiopee/Connector/Connector/computeFrictionVelocityIBM.cpp, Cassiopee/Connector/Connector/setInterpDataForGhostCellsNGon.cpp, Cassiopee/Connector/Connector/writeCoefs.cpp, Cassiopee/Converter/Converter/Converter1.cpp, Cassiopee/Converter/Converter/convertUnstruct2NGon.cpp, Cassiopee/Converter/Converter/setBCDataInGhostCells.cpp, Cassiopee/Generator/Generator/closeBorders.cpp, Cassiopee/Generator/Generator/computeCellPlanarity.cpp, Cassiopee/Generator/Generator/gapfixer.cpp, Cassiopee/Generator/Generator/mmgs.cpp, Cassiopee/Generator/Generator/pointedHat.cpp, Cassiopee/Generator/Generator/selectInsideElts.cpp, Cassiopee/Generator/Generator/stitchedHat.cpp, Cassiopee/Geom/Geom/volumeFromCrossSections.cpp, Cassiopee/Intersector/PolyMeshTools/utils.cpp, Cassiopee/KCore/KCore/Nuga/include/GeomAlgo.cxx, Cassiopee/KCore/install, Cassiopee/Post/Post/Stream/StreamSurf.cpp, Cassiopee/Post/Post/selectInteriorFaces.cpp, Cassiopee/Post/Post/zipper.cpp, Cassiopee/RigidMotion/RigidMotion/rotorMotion.cpp, Cassiopee/Transform/Transform/cart2Cyl.cpp, Cassiopee/Transform/Transform/cyl2Cart.cpp, Cassiopee/Transform/Transform/reorderAllUnstr.cpp, Cassiopee/Transform/Transform/splitConnexity.cpp
=> All: fix mem leaks, part 3

Cassiopee/Converter/Converter/IO/GenIO_fmtSU2.cpp, Cassiopee/Converter/Converter/IO/GenIO_fmtmesh.cpp, Cassiopee/Converter/Converter/IO/GenIO_fmtv3d.cpp, Cassiopee/Generator/Generator/closeBorders.cpp, Cassiopee/KCore/KCore/Array/typeId2eltString.cpp, Cassiopee/KCore/KCore/Nuga/include/Kernel.cxx, Cassiopee/KCore/KCore/Nuga/include/Mesher.h, Cassiopee/KCore/KCore/Nuga/src/Intersector.cpp, Cassiopee/KCore/KCore/empty.cpp, Cassiopee/KCore/install, Cassiopee/OCC/OCC/Atomic/projectOnEdge.cpp, Cassiopee/OCC/OCC/Atomic/projectOnFace.cpp, Cassiopee/Post/Post/zipper/Intersection.cpp, Cassiopee/Post/Post/zipper/SegmentPair.cpp, Cassiopee/Post/Post/zipper/StructBlock_iblank.cpp, Cassiopee/Post/Post/zipper/StructBlock_string.cpp, Cassiopee/Transform/Transform/mergeStructGrids.cpp
=> All: fix mem leaks, part 4

Cassiopee/Connector/Connector/setInterpData.cpp, Cassiopee/Converter/Converter/IO/GenIO_fmt.cpp, Cassiopee/KCore/KCore/empty.cpp
Fixes the error in empty_t1 introduced in part 4
=> All: fix mem leaks, part 5

Cassiopee/Apps/Apps/Fast/IBM.py, Cassiopee/Apps/Apps/Mesh/Dragon.py, Cassiopee/Connector/Connector/IBM.py, Cassiopee/Connector/Connector/OversetData.py, Cassiopee/Connector/Connector/PyTree.py, Cassiopee/Connector/Connector/cellN2OversetHoles.cpp, Cassiopee/Converter/Converter/Mpi4py.py, Cassiopee/Converter/Converter/PyTree.py, Cassiopee/Generator/Generator/IBM.py, Cassiopee/Generator/Generator/PolyC1.py, Cassiopee/Generator/doc/source/Generator.rst
+ updated doc for Generaor.close
=> All: explicit datatyping in numpy.array

Cassiopee/CPlot/apps/validCassiopee.py, Cassiopee/Connector/Connector/connector.h, Cassiopee/Connector/Connector/gatherMatching.cpp, Cassiopee/Connector/Connector/gatherMatchingNM.cpp, Cassiopee/KCore/KCore/Nuga/include/mesh_t.hxx
and also (minor points):
- CPlot: validCassiopee: create ValidData folder if initially missing
- KCore - Nuga: remove install warning
=> Connector: fix seg fault in 2D in gatherMatching

Cassiopee/Apps/test/IBMOutletControlPressure_t1.py, Cassiopee/Connector/Connector/OversetDataElsA.py, Cassiopee/Connector/test/computeFrictionVelocityPT_t1.py, Cassiopee/Connector/test/extractIBMWallFieldsPT_t1.py, Cassiopee/Connector/test/setIBCDataPT_t1.py
=> Apps/Connector: fix test cases

Cassiopee/Post/Post/IBM.py
=> [IBM] Small bug fix

Cassiopee/CPlot/apps/tkCassiopee.py, Cassiopee/CPlot/apps/tkIBC2.py
See title. The new approach is currently commented. To test and use the new approach uncomment line 36 in Cassiopee/CPlot/apps/tkCassiopee.py; the new approach is tkIBC2.
=> [IBM]  Update the GUI approach

Cassiopee/Generator/Generator/IBM.py
=> [IBM] Rectilinear bug fix

Cassiopee/Apps/Apps/Fast/IBM.py, Cassiopee/Apps/Apps/Fast/WindTunnelOutPres.py, Cassiopee/Connector/Connector/DoubleWall.py, Cassiopee/Connector/Connector/IBC/setIBCTransfers.cpp, Cassiopee/Connector/Connector/IBC/setIBCTransfersD.cpp, Cassiopee/Connector/Connector/IBM.py, Cassiopee/Connector/Connector/LBM/setInterpTransfers.cpp, Cassiopee/Connector/Connector/Mpi.py, Cassiopee/Connector/Connector/OversetData.py, Cassiopee/Connector/Connector/PyTree.py, Cassiopee/Connector/Connector/connector.h, Cassiopee/Connector/Connector/setInterpTransfers.cpp, Cassiopee/Connector/Connector/setInterpTransfersD.cpp, Cassiopee/Distributor2/Distributor2/Mpi.py
Attention: IBM mobile, calcul de reduction commenté
=> Connector: implicit_local, vector suppressed

Cassiopee/Generator/Generator/IBM.py
=> [IBM] Rectilinear granularity bug fix

.github/workflows/publish-pypi.yml, Cassiopee/KCore/install, Cassiopee/XCore/install
Uses ubuntu-20.04 LTS but not functional
=> PyPI: fix install on azure with prodmode 2

Cassiopee/Apps/Apps/Fast/IBM.py, Cassiopee/Connector/Connector/IBM.py, Cassiopee/Generator/Generator/IBM.py, Cassiopee/Geom/Geom/IBM.py
See title and bug fix - granularity based dev.
=> [IBM] Move geometry IBM functions from Apps to Geom.

Cassiopee/Generator/Generator/IBM.py
See title. These functions are not currently used. They can/will be plugged-in in the future for the dist2wall calcs in prepareIBMData for NSLaminar test cases.
=> [IBM] Move dist2wall for NSLaminar from Apps/IBM.py to Generator/IBM.py.

Cassiopee/Converter/Converter/kpython, Cassiopee/Envs/env_Cassiopee_local, Cassiopee/Envs/sh_Cassiopee_local, Cassiopee/KCore/Dist.py, Cassiopee/KCore/switchDebugMode.py, Cassiopee/KCore/switchIntSize.py
Create a sub-prod from an existing prod, where the subprod could be the name of a git branch
Int64 and debug suffixes can still be used in any order.
The marker is `_b-`:
```sh
export MACHINE=<rootprod>_b-<mysubprod>
```
For example:
```sh
export MACHINE=ld
export MACHINE=ld_i8
export MACHINE=ld_i8_DBG
export MACHINE=ld_b-dev
export MACHINE=ld_b-dev_i8
export MACHINE=ld_DBG_i8_b-dev
```
are all valid `MACHINE` names.
No need to edit KCore/installBase.py
---
Also: git hash added to KCore/installPath.py
=> KCore, Envs: create a prod for a specific branch

Cassiopee/KCore/KCore/CompGeom/bezier.cpp, Cassiopee/KCore/KCore/CompGeom/compGeom.h
Overflow in Bernstein polynomial calculation for N large: do not compute factorials
Fixes #210
=> Geom: fix bezier for N large

Cassiopee/Connector/Connector/IBM.py
=> [IBM] Add file suffixes to projection output files.

Cassiopee/Post/Post/Rotor.py
I think that these functions should remain in Post.Rotor, instead of Apps/Fast2Kim, but I'm open to discussion!
=> Post.Rotor: macro functions for KIM post-processing

Cassiopee/Apps/test/FastIBMWireMeshModel_m1.py
=> [WMM] Test case update. Check=True write files locally.

Cassiopee/Geom/Geom/IBM.py
=> [IBM] Bug fix - solid & filament

Cassiopee/Connector/Connector/IBM.py
=> [IBM] Bug fix for blanking IBC bodies based on nodes for internal flows.

Cassiopee/CPlot/apps/validCassiopee.py
- LOCAL vs GLOBAL
- branch name if different from main
=> CPlot - validCassiopee: add more info to the title bar

.github/workflows/autopep8_formatter.yml, Cassiopee/Connector/Connector/setInterpTransfers.cpp
=> Connector: nettoyage comment

Cassiopee/CPlot/apps/tkCassiopee.py, Cassiopee/CPlot/apps/tkIBC.py, Cassiopee/CPlot/apps/tkIBC2.py, Cassiopee/CPlot/apps/tkIBCOld.py
See below for two examples of the new way to add IBCs.
The previous IBC GUI is still accessible through tkIBCOld.
=> [IBM] Change the IBM GUI.

Cassiopee/KCore/test/compareSessionLogs.py
A couple of tests will necessarily return mem. leaks, do not report them
=> KCore - test: define a list of tests to ignore in debug mode

Cassiopee/Apps/Apps/Fast/Common.py, Cassiopee/Apps/test/FastIBMWireMeshModel_m1.py
These two files are modified to match the latest commit in Fast (pull request 69)
=> Apps: update files according to new Fast load/save functions

Cassiopee/Apps/test/FastIBMO_m1.py, Cassiopee/Apps/test/FastIBMO_t1.py
This pull request is linked to the Fast PR#76 (https://github.com/onera/Fast/pull/76).
=> Apps: testcase modif to avoid regression

Cassiopee/Apps/Apps/Fast/IBM.py, Cassiopee/Connector/Connector/IBM.py, Cassiopee/Connector/Connector/compactTransfers.py
=> Connector: nearmatch conservatif

Cassiopee/Connector/Connector/IBM.py
Cmpi.allgather on a dict returns a dict, while kpython returns a list containing the dict (-> [dict])
=> X_IBM: bug fix _buildConservativeFlux

Cassiopee/Distributor2/Distributor2/PyTree.py
=> [DISTRIB] Bug fix for new skeleton Tree from file distribution.

Cassiopee/Geom/Geom/IBM.py, Cassiopee/Geom/test/changeIBCTypePT_t1.py
see title. Extend the function to include the future linearized wall modeling IBMs.
=> [IBM] Mod to changeIBCType.

Cassiopee/Intersector/doc/source/_templates/mine.html, docs/doc/Intersector.html
Update Intersector doc template as the other modules. Correct Intersector.html as such.
=> Intersector: update doc template

Cassiopee/Apps/Apps/Fast/IBM.py, Cassiopee/Connector/Connector/IBM.py, Cassiopee/Connector/Connector/commonInterpTransfers.h, Cassiopee/Connector/Connector/commonInterpTransfersD_reorder_19eq.h, Cassiopee/Connector/Connector/commonInterpTransfersD_reorder_5eq.h, Cassiopee/Connector/Connector/commonInterpTransfersD_reorder_6eq.h, Cassiopee/Connector/Connector/commonInterpTransfersD_reorder_6eq_gradP.h, Cassiopee/Connector/Connector/commonInterpTransfersD_reorder_neq.h, Cassiopee/Connector/Connector/commonInterpTransfers_reorder_19eq.h, Cassiopee/Connector/Connector/commonInterpTransfers_reorder_5eq.h, Cassiopee/Connector/Connector/commonInterpTransfers_reorder_6eq.h, Cassiopee/Connector/Connector/commonInterpTransfers_reorder_6eq_gradP.h, Cassiopee/Connector/Connector/commonInterpTransfers_reorder_neq.h, Cassiopee/Connector/Connector/compactTransfers.py, Cassiopee/Connector/Connector/connector.h, Cassiopee/Connector/Connector/setInterpData.cpp, Cassiopee/Connector/doc/source/Connector.rst, Cassiopee/Connector/test/setInterpDataPT_t9.py, Cassiopee/KCore/KCore/Interp/CompInterpolatedPtInRefElementF.for, Cassiopee/KCore/KCore/Interp/Interp.cpp, Cassiopee/KCore/KCore/Interp/Interp2.cpp, Cassiopee/KCore/KCore/Interp/InterpAdt.cpp, Cassiopee/KCore/KCore/Interp/InterpAdt.h, Cassiopee/KCore/KCore/Interp/InterpCart.cpp, Cassiopee/KCore/KCore/Interp/InterpCart.h, Cassiopee/KCore/KCore/Interp/InterpData.h, Cassiopee/KCore/KCore/Interp/commonTypesForExtrapAndInterp.h
interpolation polynome lagrange ordre 4 pour grille curvi et cartesienne.
pas de regression sur ld et juno.
=> KCore+Connector: interp Lagrange O4 + nearmatch conservatif 2x2x1

Cassiopee/Generator/Generator/PyTree.py, Cassiopee/KCore/KCore/Connect/v_cleanConnectivity.cpp
validCassiopee was not returning any errors on my account.
It did globally over night, so I revert this commit while I am investigating this issue.
=> Revert "Generator: close mesh in api3"

Cassiopee/Transform/Transform/dual.cpp, Cassiopee/Transform/Transform/joinAll.cpp
Regressions:
- Topologically
Apps            : createDragonMesh_t1.py
Generator       : getSmoothNormalMap_t1.py
Intersector     : selfX_t1.py 
Intersector     : xcellnSph6PT_t1.py 
Transform       : dualPT_t1.py     
Transform       : dual_t1.py      
Transform       : joinPT_t2.py 
Transform       : reorderPT_t1.py 
Transform       : splitMultiplePts_t1.py     
- Geometrically
Generator       : getSmoothNormalMap_t1.py 
NB: array test, so getSmoothNormalMap_t1 can't be run geometrically
=> Transform: call new version of cleanConnectivity in joinAll and dual

Cassiopee/Envs/sh_Cassiopee_local
proposed bug fix to run on sator.
=> [INSTALL] Bug fix sator install

Cassiopee/KCore/KCore/CompGeom/RotateMesh.cpp, Cassiopee/KCore/KCore/CompGeom/compGeom.h
=> [F2Cpp] Update header file and beginnig of notation harmonization

Cassiopee/Connector/Connector/KInterp/KMesh.cpp, Cassiopee/Connector/Connector/KInterp/KMesh.h, Cassiopee/Connector/Connector/blankCells.cpp, Cassiopee/Generator/Generator/bboxIntersection.cpp, Cassiopee/Generator/Generator/checkPointInCEBB.cpp, Cassiopee/Generator/Generator/close.cpp, Cassiopee/Generator/Generator/extendCartGrids.cpp, Cassiopee/Generator/Generator/getBBoxOfCells.cpp, Cassiopee/Generator/Generator/octree.cpp, Cassiopee/Generator/Generator/octree3.cpp, Cassiopee/Geom/Geom/volumeFromCrossSections.cpp, Cassiopee/KCore/KCore/CompGeom/compGeom.cpp, Cassiopee/KCore/KCore/CompGeom/compGeom.h, Cassiopee/KCore/KCore/CompGeom/delaunay.cpp, Cassiopee/KCore/KCore/Interp/InterpAdt.cpp, Cassiopee/KCore/KCore/kcore.cpp, Cassiopee/Post/Post/computeIndicatorValue.cpp, Cassiopee/Post/Post/enforceIndicatorNearBodies.cpp, Cassiopee/Post/Post/zipper/StructBlock.cpp, Cassiopee/Post/Post/zipper/StructBlock.h, Cassiopee/Transform/Transform/deformMeshStruct.cpp, Cassiopee/Transform/Transform/mergeCartGrids.cpp, Cassiopee/Transform/Transform/reorderAll.cpp
No regression.
k6boundbox_ -> boundingBoxStruct()
k6boundboxunstr -> boundingBoxUnstruct()
k6boundboxofstructcell -> boundingBoxOfStructCell()
The later has also been updated with a "loc" argument, to operate on cell centers and cell vertices (cf. StructBlock.cpp).
=> KCore & all: rm fortran functions for boundingBox, part 1

Cassiopee/Envs/env_Cassiopee_local, Cassiopee/Envs/sh_Cassiopee_local, Cassiopee/KCore/config.py, Cassiopee/KCore/installBase.py
-  sh_cassiopee_local: MACHINE a la priorité sur uname
- sh_cassiopee_local: homogenisation MACHINE et ELSAPROD : MACHINE_i8, updater MACHINE
=> Envs: MACHINE a la priorité sur uname, homogenisation MACHINE

Cassiopee/KCore/KCore/Metric/compNormUnstrSurf.cpp, Cassiopee/KCore/KCore/Metric/metric.h, Cassiopee/Post/Post/Fortran/integNormStruct.cpp, Cassiopee/Post/Post/Fortran/integNormUnstruct.cpp, Cassiopee/Post/Post/Fortran/integUnstruct.cpp, Cassiopee/Post/Post/PyTree.py, Cassiopee/Post/Post/integNorm.cpp, Cassiopee/Post/Post/post.h, Cassiopee/Post/test/integNormPT_t2.py, Cassiopee/Post/test/integPT_t3.py
No regression.
New test-case for integ.cpp (integPT_t3.py), new test-case for integNorm.cpp (integNormPT_t2.py).
=> Post: update integNorm.cpp with new test-case and ME capabilities.

Cassiopee/KCore/KCore/Fld/FldArray.h, Cassiopee/Post/Post/Fortran/integStruct.cpp, Cassiopee/Post/Post/Stream2/py_stream_line.cpp, Cassiopee/Post/Post/computeCurl.cpp, Cassiopee/Post/Post/computeDiff.cpp, Cassiopee/Post/Post/computeDiv.cpp, Cassiopee/Post/Post/computeDiv2.cpp, Cassiopee/Post/Post/computeGrad.cpp, Cassiopee/Post/Post/computeGrad2.cpp, Cassiopee/Post/Post/computeNormCurl.cpp, Cassiopee/Post/Post/computeNormGrad.cpp, Cassiopee/Post/Post/computeVariables.cpp, Cassiopee/Post/Post/enforceIndicatorForCoarsestLevel.cpp, Cassiopee/Post/Post/enforceIndicatorForFinestLevel.cpp, Cassiopee/Post/Post/enforceIndicatorNearBodies.cpp, Cassiopee/Post/Post/extractMesh.cpp, Cassiopee/Post/Post/integ.cpp, Cassiopee/Post/Post/integNorm.cpp, Cassiopee/Post/Post/integNormProd.cpp, Cassiopee/Post/Post/perlinNoise.cpp, Cassiopee/Post/Post/projectCloudSolution2Triangle.cpp, Cassiopee/Post/Post/selectExteriorElts.cpp, Cassiopee/Post/Post/selectExteriorFaces.cpp, Cassiopee/Post/Post/selectExteriorFacesStructured.cpp, Cassiopee/Post/Post/usurp.cpp
- Use buildArray3 instead of buildArray
- Add api to buildArray3 for struct arrays
- Fix a few warnings
- getDim for NGon arrays only for the time being
No regressions
=> Post: more buildArray3

Cassiopee/Transform/Transform/addkplane.cpp, Cassiopee/Transform/Transform/computeDeformationVector.cpp, Cassiopee/Transform/Transform/deform.cpp, Cassiopee/Transform/Transform/deform2.cpp, Cassiopee/Transform/Transform/deformMeshStruct.cpp, Cassiopee/Transform/Transform/projectAllDirs.cpp, Cassiopee/Transform/Transform/projectDir.cpp, Cassiopee/Transform/Transform/projectOrtho.cpp, Cassiopee/Transform/Transform/projectOrthoSmooth.cpp
=> Transform: more buildArray3

Cassiopee/Dist2Walls/Dist2Walls/Eikonal/eikonal.cpp, Cassiopee/Dist2Walls/Dist2Walls/distance2walls.cpp, Cassiopee/Dist2Walls/Dist2Walls/distance2walls_ortho.cpp, Cassiopee/Dist2Walls/Dist2Walls/distance2walls_orthosigned.cpp, Cassiopee/Dist2Walls/Dist2Walls/distance2walls_signed.cpp, Cassiopee/Geom/Geom/Geom1.cpp, Cassiopee/Geom/Geom/Geom2.cpp, Cassiopee/Geom/Geom/axisym.cpp, Cassiopee/Geom/Geom/bezier.cpp, Cassiopee/Geom/Geom/getCurvatureAngle.cpp, Cassiopee/Geom/Geom/getCurvatureHeight.cpp, Cassiopee/Geom/Geom/getCurvatureRadius.cpp, Cassiopee/Geom/Geom/getSharpestAngleForVertices.cpp, Cassiopee/Geom/Geom/lineGenerate.cpp, Cassiopee/Geom/Geom/lineGenerate2.cpp, Cassiopee/Geom/Geom/naca.cpp, Cassiopee/Geom/Geom/nurbs.cpp, Cassiopee/Geom/Geom/polyline.cpp, Cassiopee/Geom/Geom/spline.cpp, Cassiopee/Geom/Geom/torus.cpp, Cassiopee/Geom/Geom/volumeFromCrossSections.cpp, Cassiopee/Transform/Transform/projectRay.cpp
=> Dist2Walls/Geom: more buildArray3, add api to buildArray3 always

Cassiopee/Apps/Apps/Mesh/Mirabelle3.py, Cassiopee/Converter/Converter/PyTree.py, Cassiopee/Generator/Generator/PyTree.py, Cassiopee/Generator/test/refinePT_t1.py, Cassiopee/Generator/test/refinePT_t2.py
Generator.refinePT_t1.py: anticipated regression for ref2 & ref3 (add new features, BCs for factor<1)) .
=> Mirabelle3 ; refine; Converter: mergeBCs: suppress prefix "Merged:"
